version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dora-postgres
    environment:
      POSTGRES_DB: dora_metrics
      POSTGRES_USER: dora_user
      POSTGRES_PASSWORD: dora_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dora/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dora_user -d dora_metrics"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
